name: PR CI (ts-check, lint, test)

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.19

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: TypeScript check
        run: bun run ts

      - name: Lint
        run: bun run lint

      - name: Unit tests
        run: bun run test

      - name: Compile extension
        run: bun run compile

      - name: VSCode integration tests (e2e)
        run: xvfb-run -a bun run test:e2e
